"""Create complaint table

Revision ID: 066a94333bad
Revises: 
Create Date: 2025-04-01 19:11:19.897671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066a94333bad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('ticket_number', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.drop_table('complaints')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('complaint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticket_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='complaints_pkey')
    )
    op.drop_table('complaint')
    # ### end Alembic commands ###
